version: '3.8'

services:
  web:
    build:
      context: .
      target: runner
    container_name: portfolio-web-prod
    restart: always
    expose:
      - "3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET:-chave_super_secreta_producao_123}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-dev@franklyndev.com.br}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin@123}
    volumes:
      - portfolio_uploads_prod:/app/public/uploads
    networks:
      - coolify

volumes:
  portfolio_uploads_prod:

networks:
  coolify:
    external: true
