import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#060e20',
        'on-secondary': '#003824',
        surface: '#0b1326',
        background: '#0b1326',
        'on-secondary-fixed-variant': '#005236',
        error: '#ffb4ab',
        'on-tertiary-fixed': '#0b1c30',
        'secondary-fixed-dim': '#4edea3',
        'on-tertiary-container': '#506076',
        'primary-fixed': '#7df4ff',
        'surface-bright': '#31394d',
        'on-tertiary-fixed-variant': '#38485d',
        'surface-dim': '#0b1326',
        'surface-container-high': '#222a3d',
        'inverse-surface': '#dae2fd',
        'on-background': '#dae2fd',
        'on-secondary-fixed': '#002113',
        'surface-container-highest': '#2d3449',
        'error-container': '#93000a',
        'inverse-on-surface': '#283044',
        outline: '#849495',
        'surface-variant': '#2d3449',
        'on-surface': '#dae2fd',
        'on-primary-container': '#006970',
        'outline-variant': '#3b494b',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-primary-fixed-variant': '#004f54',
        'on-primary-fixed': '#002022',
        'secondary-fixed': '#6ffbbe',
        'surface-container-low': '#131b2e',
        'secondary-container': '#00a572',
        'primary-container': '#00f0ff',
        'surface-container': '#171f33',
        'on-primary': '#00363a',
        secondary: '#4edea3',
        'on-tertiary': '#213145',
        'tertiary-fixed': '#d3e4fe',
        'tertiary-container': '#cadbf5',
        'on-error': '#690005',
        tertiary: '#f3f6ff',
        primary: '#dbfcff',
        'primary-fixed-dim': '#00dbe9',
        'inverse-primary': '#006970',
        'surface-tint': '#00dbe9',
        'on-surface-variant': '#b9cacb',
        'on-secondary-container': '#00311f',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '48px',
        xl: '80px',
        md: '24px',
        sm: '16px',
        xs: '8px',
        gutter: '24px',
        base: '4px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['"Work Sans"', 'sans-serif'],
        'body-lg': ['"Work Sans"', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        'code-label': ['"Space Grotesk"', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        h1: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'code-label': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
